import React from "react";
import "./global.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "../utils/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html className={inter.className} lang="en">
        {children}
      </html>
    </Providers>
  );
}
