import { SignInButton, SignOutButton } from "@clerk/clerk-react";
import { SignedIn, SignedOut } from "@clerk/nextjs";

import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SignedIn>
          You are signed in <SignOutButton />{" "}
        </SignedIn>
        <SignedOut>
          You are signed out <SignInButton />
        </SignedOut>
      </main>
    </>
  );
};

export default Home;
