import React from "react";
import type { Metadata } from "next";
import NavBar from "./components/NavBar/NavBar";
import SideNav from "./components/SideNav/SideNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function NavLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <NavBar />
      <section className="flex h-[calc(100svh-64px)]">
        <SideNav />
        <main className="h-full w-full p-8 ">{children}</main>
      </section>
    </>
  );
}
