name: Production Database Migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Production Migrations
        run: npx prisma migrate deploy --schema  packages/backend/src/prisma/schema.prisma
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
