name: Staging Database Migrations

on:
  push:
    branches:
      - staging

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Staging Migrations
        run: npx prisma migrate deploy --preview-feature --schema  packages/backend/src/prisma/schema.prisma
        env:
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
